# Generated by Django 4.2.3 on 2023-09-20 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FoodSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_space_type', models.CharField(choices=[('Ресторан', 'Ресторан'), ('Кафе', 'Кафе'), ('Буфет', 'Буфет'), ('Фудкорт', 'Фудкорт'), ('Столовая', 'Столовая')], max_length=50, verbose_name='Тип места питания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('cuisine', models.CharField(choices=[('Азиатский', 'Азиатский'), ('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Индийская', 'Индийская')], max_length=100, verbose_name='Кухня')),
                ('meal_options', multiselectfield.db.fields.MultiSelectField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=100, verbose_name='Прием пищи')),
                ('opening_hours', models.TimeField(verbose_name='Часы открытия')),
                ('closing_hours', models.TimeField(verbose_name='Часы закрытия')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Wi-Fi', 'Wi-Fi'), ('Парковка', 'Парковка'), ('Доступ для инвалидных колясок', 'Доступ для инвалидных колясок'), ('Принимаются бронирования', 'Принимаются бронирования'), ('Доставка еды', 'Доставка еды'), ('Еда на вынос', 'Еда на вынос'), ('Наличие мест на открытом воздухе', 'Наличие мест на открытом воздухе')], max_length=255, verbose_name='Удобства')),
                ('price_category', models.CharField(choices=[('Доступные цены', 'Доступные цены'), ('Средние цен', 'Средние цены'), ('Выше средних цен', 'Выше средних цен'), ('Высокие цены', 'Высокие цены')], max_length=20, verbose_name='Категория цен')),
            ],
            options={
                'verbose_name': 'Место питания',
                'verbose_name_plural': 'Места питания',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='')),
            ],
            options={
                'verbose_name': 'Изображение места питания',
                'verbose_name_plural': 'Изображения места питания',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
            ],
            options={
                'verbose_name': 'Бронь столика',
                'verbose_name_plural': 'Бронь столиков',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка персонала')),
                ('food_quality_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка качества пищи')),
                ('ambiance_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка атмосферы')),
                ('service_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка обслуживания')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
