# Generated by Django 4.2.4 on 2023-08-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_space_type', models.CharField(choices=[('Ресторан', 'Ресторан'), ('Кафе', 'Кафе'), ('Буфет', 'Буфет'), ('Фудкорт', 'Фудкорт'), ('Столовая', 'Столовая')], max_length=50, verbose_name='Тип места питания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('cuisine', models.CharField(choices=[('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Индийская', 'Индийская'), ('Азиатский', 'Азиатский')], max_length=100, verbose_name='Кухня')),
                ('meal_options', multiselectfield.db.fields.MultiSelectField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=100, verbose_name='Прием пищи')),
                ('opening_hours', models.TimeField(verbose_name='Часы открытия')),
                ('closing_hours', models.TimeField(verbose_name='Часы закрытия')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('wifi', 'Есть Wi-Fi'), ('parking', 'Есть парковка'), ('wheelchair_access', 'Есть доступ для инвалидных колясок'), ('reservations', 'Принимаются бронирования'), ('delivery', 'Доставка еды'), ('takeout', 'Еда на вынос'), ('outdoor_seating', 'Наличие мест на открытом воздухе')], max_length=255, verbose_name='Удобства')),
                ('price_category', models.CharField(choices=[('affordable', 'Доступные цены'), ('moderate', 'Средние цены'), ('higher', 'Выше средних цен'), ('luxury', 'Высокие цены')], max_length=20, verbose_name='Категория цен')),
            ],
            options={
                'verbose_name': 'Место питания',
                'verbose_name_plural': 'Места питания',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Фотография профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка персонала')),
                ('food_quality_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка качества пищи')),
                ('ambiance_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка атмосферы')),
                ('service_rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], verbose_name='Оценка обслуживания')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование столика',
                'verbose_name_plural': 'Бронирования столиков',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма заказа')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants', verbose_name='Изображение')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_space.foodspace')),
            ],
            options={
                'verbose_name': 'Изображение места питания',
                'verbose_name_plural': 'Изображения места питания',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('food_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_space.foodspace', verbose_name='Место питания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
