# Generated by Django 4.2.4 on 2023-08-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронь столика', 'verbose_name_plural': 'Бронь столиков'},
        ),
    ]
