# Generated by Django 4.2.4 on 2023-08-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_space', '0004_alter_order_options_remove_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
