# Generated by Django 4.2.4 on 2023-08-13 20:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_space', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodspace',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wi-Fi', 'Wi-Fi'), ('Парковка', 'Парковка'), ('Доступ для инвалидных колясок', 'Доступ для инвалидных колясок'), ('Принимаются бронирования', 'Принимаются бронирования'), ('Доставка еды', 'Доставка еды'), ('Еда на вынос', 'Еда на вынос'), ('Наличие мест на открытом воздухе', 'Наличие мест на открытом воздухе')], max_length=255, verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='foodspace',
            name='cuisine',
            field=models.CharField(choices=[('Азиатский', 'Азиатский'), ('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Индийская', 'Индийская')], max_length=100, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='foodspace',
            name='price_category',
            field=models.CharField(choices=[('Доступные цены', 'Доступные цены'), ('Средние цен', 'Средние цены'), ('Выше средних цен', 'Выше средних цен'), ('Высокие цены', 'Высокие цены')], max_length=20, verbose_name='Категория цен'),
        ),
    ]
