# Generated by Django 4.2.3 on 2023-09-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verify_code',
            new_name='code',
        ),
    ]
